import React from "react";

export const MENUITEMS = [
  {
    title: "Absence",
    icon: <i className="pe-7s-portfolio pe-lg"></i>,
    type: "sub",
    path: `${process.env.PUBLIC_URL}/absence`,
    active: false,
    bookmark: true,
    access: "absence",
    children: [
      { title: "absence", type: "sub" },
      {
        title: "absence list",
        type: "link",
        path: `${process.env.PUBLIC_URL}/absence`,
      },
    ],
  },
  {
    title: "admins",
    icon: <i className="pe-7s-portfolio pe-lg"></i>,
    type: "sub",
    path: `${process.env.PUBLIC_URL}/admins`,
    active: false,
    bookmark: true,
    access: "admins",
    children: [
      { title: "admins", type: "sub" },
      {
        title: "admins List",
        type: "link",
        path: `${process.env.PUBLIC_URL}/admins`,
      },
    ],
  },
  {
    title: "All data",
    icon: <i className="pe-7s-portfolio pe-lg"></i>,
    type: "link",
    path: `${process.env.PUBLIC_URL}/`,
    active: true,
    bookmark: true,
    access: "dashboard",
    children: [
      { title: "dashboard", type: "sub" },
      {
        title: "dashboard",
        type: "link",
        path: `${process.env.PUBLIC_URL}/dashboard`,
      },
    ],
  },
  {
    title: "Branches",
    icon: <i className="pe-7s-portfolio pe-lg"></i>,
    type: "sub",
    path: `${process.env.PUBLIC_URL}/branches`,
    active: false,
    bookmark: true,
    access: "branches",
    children: [
      { title: "Branches", type: "sub" },
      {
        title: "Branches List",
        type: "link",
        path: `${process.env.PUBLIC_URL}/branches`,
      },
    ],
  },
  {
    title: "Complains & Exceptions",
    icon: <i className="pe-7s-portfolio pe-lg"></i>,
    type: "sub",
    path: `${process.env.PUBLIC_URL}/notes`,
    active: false,
    bookmark: true,
    access: "notes",
    children: [
      { title: "Complains & Exeptions", type: "sub" },
      {
        title: "notes List",
        type: "link",
        path: `${process.env.PUBLIC_URL}/notes`,
      },
    ],
  },
  {
    title: "Feedback",
    icon: <i className="pe-7s-portfolio pe-lg"></i>,
    type: "sub",
    path: `${process.env.PUBLIC_URL}/feedback`,
    active: false,
    bookmark: true,
    access: "feedback",
    children: [
      { title: "Feedback", type: "sub" },
      {
        title: "Feedback List",
        type: "link",
        path: `${process.env.PUBLIC_URL}/feedback`,
      },
    ],
  },
  {
    title: "Finances",
    icon: <i className="pe-7s-portfolio pe-lg"></i>,
    type: "sub",
    path: `${process.env.PUBLIC_URL}/Expenses`,
    active: false,
    bookmark: true,
    access: "expenses",
    children: [
      { title: "Finances", type: "sub" },
      {
        title: "Add Expenses",
        type: "link",
        path: `${process.env.PUBLIC_URL}/Expenses`,
      },
      {
        title: "Refundes",
        type: "link",
        path: `${process.env.PUBLIC_URL}/Refunds`,
      },
      {
        title: "Debtors",
        type: "link",
        path: `${process.env.PUBLIC_URL}/debtors`,
      },
      {
        title: "Branches payment",
        type: "link",
        path: `${process.env.PUBLIC_URL}/branch-payments`,
      },
    ],
  },
  {
    title: "Forms",
    icon: <i className="pe-7s-portfolio pe-lg"></i>,
    type: "sub",
    path: `${process.env.PUBLIC_URL}/forms_list`,
    active: false,
    bookmark: true,
    access: "questionnaire",
    children: [
      { title: "Questionnaire", type: "sub" },
      {
        title: "Forms List",
        type: "link",
        path: `${process.env.PUBLIC_URL}/forms_list`,
      },
      {
        title: "Create Form",
        type: "link",
        path: `${process.env.PUBLIC_URL}/questionnaire`,
      },
    ],
  },
  {
    title: "Groups",
    icon: <i className="pe-7s-portfolio pe-lg"></i>,
    type: "sub",
    path: `${process.env.PUBLIC_URL}/groups`,
    active: false,
    bookmark: true,
    access: "groups",
    children: [
      { title: "Groups", type: "sub" },
      {
        title: "Groups List",
        type: "link",
        path: `${process.env.PUBLIC_URL}/groups`,
      },
    ],
  },
  {
    title: "Levels",
    icon: <i className="pe-7s-portfolio pe-lg"></i>,
    type: "sub",
    path: `${process.env.PUBLIC_URL}/levels/list`,
    active: false,
    bookmark: true,
    access: "levels",
    children: [
      { title: "Levels", type: "sub" },
      {
        title: "Level List",
        type: "link",
        path: `${process.env.PUBLIC_URL}/levels/list`,
      },
      {
        title: "placement test",
        type: "link",
        path: `${process.env.PUBLIC_URL}/levels/exams`,
      },
      {
        title: "placement Attachment",
        type: "link",
        path: `${process.env.PUBLIC_URL}/levels/placementAttachment`,
      },
      {
        title: "Analysis Question",
        type: "link",
        path: `${process.env.PUBLIC_URL}/levels/AnalysisQuestion`,
      },
    ],
  },
  {
    title: "packages",
    icon: <i className="pe-7s-portfolio pe-lg"></i>,
    type: "sub",
    path: `${process.env.PUBLIC_URL}/SubscriptionList`,
    active: false,
    bookmark: true,
    access: "subscription",
    children: [
      { title: "Subscription", type: "sub" },
      {
        title: "packages List",
        type: "link",
        path: `${process.env.PUBLIC_URL}/SubscriptionList`,
      },
    ],
  },
  {
    title: "posts",
    icon: <i className="pe-7s-portfolio pe-lg"></i>,
    type: "sub",
    path: `${process.env.PUBLIC_URL}/posts`,
    active: false,
    bookmark: true,
    access: "posts",
    children: [
      { title: "posts", type: "sub" },
      {
        title: "posts List",
        type: "link",
        path: `${process.env.PUBLIC_URL}/posts`,
      },
    ],
  },
  {
    title: "Students",
    icon: <i className="pe-7s-portfolio pe-lg"></i>,
    type: "sub",
    path: `${process.env.PUBLIC_URL}/students/list`,
    active: true,
    bookmark: true,
    access: "students",
    children: [
      { title: "Students", type: "sub" },
      {
        title: "List",
        type: "link",
        path: `${process.env.PUBLIC_URL}/students/list`,
      },
    ],
  },
  {
    title: "Technical support",
    icon: <i className="pe-7s-portfolio pe-lg"></i>,
    type: "sub",
    path: `${process.env.PUBLIC_URL}/teckets`,
    active: true,
    bookmark: true,
    access: "tickets",
    children: [
      { title: "Tickets", type: "sub" },
      {
        title: "Display tickets",
        type: "link",
        path: `${process.env.PUBLIC_URL}/teckets`,
      },
    ],
  },
  {
    title: "Tracks",
    icon: <i className="pe-7s-portfolio pe-lg"></i>,
    type: "sub",
    path: `${process.env.PUBLIC_URL}/Tracks/list`,
    active: true,
    bookmark: true,
    access: "tracks",
    children: [
      { title: "Tracks", type: "sub" },
      {
        title: "List",
        type: "link",
        path: `${process.env.PUBLIC_URL}/Tracks/list`,
      },
    ],
  },
];
